# Copyright 2025 The KCP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  name: examples-apiexport-multicluster
spec:
  latestResourceSchemas: []
  permissionClaims:
  - all: true
    group: ""
    resource: configmaps
  - all: true
    group: ""
    resource: secrets
---
apiVersion: tenancy.kcp.io/v1alpha1
kind: WorkspaceType
metadata:
  name: examples-apiexport-multicluster
spec:
  defaultAPIBindings:
  - export: examples-apiexport-multicluster
    path: root
  defaultChildWorkspaceType:
    name: universal
    path: root
  extend:
    with:
    - name: universal
      path: root
---
apiVersion: tenancy.kcp.io/v1alpha1
kind: Workspace
metadata:
  name: example1
spec:
  type:
    name: examples-apiexport-multicluster
    path: root
---
apiVersion: tenancy.kcp.io/v1alpha1
kind: Workspace
metadata:
  name: example2
spec:
  type:
    name: examples-apiexport-multicluster
    path: root
---
apiVersion: tenancy.kcp.io/v1alpha1
kind: Workspace
metadata:
  name: example3
spec:
  type:
    name: examples-apiexport-multicluster
    path: root

